### ISSUE TITLE
Add an option to addUserAction() method to set to unchecked the checkbox on 2nd page

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/Uninstaller#2]
Up to now every action defined with addUserAction() method have their corresponding checkbox checked on 2nd page (choice and confirmation).
It would be nice to have an option to unchecked some of them by default.

Exemple:

- [ ] effacer l'espace de nom de paramètre de blog "a11yConfig"
- [ ] effacer l'espace de nom de paramètres global "a11yConfig"
- [ ] effacer l'espace de nom de paramètres "a11yConfig"
- [ ] effacer les préférences utilisateurs "a11yConfig"
- [ ] effacer les préférences globales "a11yConfig"
- [ ] effacer les préférences "a11yConfig"
- [ ] supprimer le numéro de version de "a11yConfig"
- [x] effacer les fichiers et répertoires du plugin "a11yConfig"

This way we may reproduce the actual system where deleting a plugin does not delete all settings/preferences, …

**Comment by JcDenis** [comment]
ça serait au module ou au cleaner de définir la valeur par défaut ?

**Comment by franck-paul** [comment]
Ah, bonne question…

**Comment by franck-paul** [comment]
Si c'est le cleaner alors décoché si la suppression est irrémédiable (settings/préférences/var) et coché si ça n'est pas grave (suppression plugin, cache) vu que le cache n'a pas vocation à être permanent et le plugin peut être réinstallé, en gros

**Comment by franck-paul** [comment]
Ensuite le module pourrait décider de modifier cette valeur, mais pour des cas très spécifiques je pense.

**Comment by JcDenis** [comment]
Je vois ça comme ça oui: le Cleaner met une valeur par défaut que le module peut surcharger.
