### ISSUE TITLE
erreur à l'installation

### ISSUE THREAD

**Issue by brol** [JcDenis/Uninstaller#4]
coucou, j'ai voulu mettre à jour un de tes plugin (dcAdvanced) et apparemment ce n'est pas possible car Uninstaller n'était pas installé, j'ai donc procédé à son installation via la mise à jour manuelle (lien direct vers le plugin ici), et j'ai ça en retour quand j'affiche la page des plugins !
2.27-dev-r20230529.0715
php8.1
remboursez !

<html><body>

Fatal  error: Traits cannot have constants in  F:\wamp64\www\labodc2\all-blogs\plugins\Uninstaller\src\Helper\DirTrait.php  on line 26
--

1 | 0.0002 | 361344 | {main}(  ) | ...\plugins.php:0
2 | 0.8657 | 3601664 | adminPlugins::render(  ) | ...\plugins.php:317
3 | 0.8771 | 3668504 | adminModulesList->displayModules( $cols = [0 => 'expander', 1 => 'icon', 2 => 'name', 3 => 'version', 4 => 'desc', 5 => 'distrib', 6 => 'deps'], $actions = [0 => 'deactivate', 1 => 'delete', 2 => 'behavior'], $nav_limit = ??? ) | ...\plugins.php:185
4 | 0.8779 | 3668488 | adminModulesList->getActions( $define = class  dcModuleDefine { private string $id = 'aboutConfig'; private array  $implies = []; private array $missing = []; private array $using = [];  private array $properties = ['name' => 'about:config', 'desc' =>  'Manage every blog configuration directive', 'author' => 'Olivier  Meunier', 'version' => '1.0', 'type' => 'plugin', 'state' => 0,  'root' =>  'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../plugins\\aboutConfig',  'namespace' => '\\Dotclear\\Plugin\\aboutConfig', 'root_writable'  => TRUE, 'distributed' => TRUE, 'sid' => 'aboutconfig', 'label'  => 'aboutConfig', 'sname' => 'aboutconfig']; private array  $default = ['state' => 1, 'root' => NULL, 'namespace' => NULL,  'root_writable' => FALSE, 'distributed' => FALSE, 'name' =>  'undefined', 'desc' => '', 'author' => '', 'version' => '0',  'type' => 'undefined', 'permissions' => NULL, 'priority' =>  1000, 'standalone_config' => FALSE, 'requires' => [...],  'settings' => [...], 'label' => '', 'support' => '', 'details'  => '', 'repository' => '', 'parent' => NULL, 'tplset' =>  'mustek', 'file' => '', 'current_version' => 0, 'section' =>  '', 'tags' => '', 'sshot' => '', 'score' => 0, 'dc_min' =>  '', 'sid' => '', 'sname' => ''] }, $actions = [0 => 'deactivate', 1 => 'delete', 2 => 'behavior'] ) | ...\lib.moduleslist.php:966
5 | 0.8779 | 3668992 | dcCore->callBehavior( $behavior = 'adminModulesListGetActionsV2', ...$args = variadic(class  adminModulesList { public $modules = class dcPlugins { protected  $safe_mode = FALSE; protected $path = [...]; protected $defines = [...];  protected $errors = [...]; protected $modules_ids = [...]; protected  $disabled_mode = FALSE; protected $ns = 'admin'; protected $define =  class dcModuleDefine { ... }; protected $id = NULL; protected $mroot =  NULL; protected $namespace = NULL; protected $type = 'plugin' }; public  $store = class dcStore { public $modules = class dcPlugins { ... };  protected $user_agent = 'Dotclear/2.27-dev-r20230529.0715)'; protected  $xml_url = 'https://update.dotaddict.org/dc2/plugins.xml'; protected  $data = [...]; protected $defines = [...] }; protected $list_id =  'plugin-activate'; protected $defines = [7 => class dcModuleDefine {  ... }, 3 => class dcModuleDefine { ... }, 2 => class  dcModuleDefine { ... }, 18 => class dcModuleDefine { ... }, 5 =>  class dcModuleDefine { ... }, 20 => class dcModuleDefine { ... }, 22  => class dcModuleDefine { ... }, 24 => class dcModuleDefine { ...  }, 10 => class dcModuleDefine { ... }, 0 => class dcModuleDefine {  ... }, 42 => class dcModuleDefine { ... }, 39 => class  dcModuleDefine { ... }, 11 => class dcModuleDefine { ... }, 13 =>  class dcModuleDefine { ... }, 1 => class dcModuleDefine { ... }, 4  => class dcModuleDefine { ... }, 25 => class dcModuleDefine { ...  }, 9 => class dcModuleDefine { ... }, 26 => class dcModuleDefine {  ... }, 21 => class dcModuleDefine { ... }, 12 => class  dcModuleDefine { ... }, 28 => class dcModuleDefine { ... }, 29 =>  class dcModuleDefine { ... }, 30 => class dcModuleDefine { ... }, 8  => class dcModuleDefine { ... }, 31 => class dcModuleDefine { ...  }, 32 => class dcModuleDefine { ... }, 40 => class dcModuleDefine {  ... }, 33 => class dcModuleDefine { ... }, 19 => class  dcModuleDefine { ... }, 6 => class dcModuleDefine { ... }, 36 =>  class dcModuleDefine { ... }, 27 => class dcModuleDefine { ... }, 34  => class dcModuleDefine { ... }, 14 => class dcModuleDefine { ...  }, 35 => class dcModuleDefine { ... }, 15 => class dcModuleDefine {  ... }, 43 => class dcModuleDefine { ... }, 16 => class  dcModuleDefine { ... }, 37 => class dcModuleDefine { ... }, 38 =>  class dcModuleDefine { ... }, 17 => class dcModuleDefine { ... }, 41  => class dcModuleDefine { ... }, 23 => class dcModuleDefine { ...  }]; protected $config_define = NULL; protected $config_class = '';  protected $config_file = ''; protected $config_content = ''; protected  $path =  'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins';  protected $path_writable = TRUE; protected $path_pattern =  'F\\:\\\\wamp64\\\\www\\\\labodc2\\\\dotclear\\\\inc/\\.\\./\\.\\./all\\-blogs/plugins';  protected $page_url = 'plugins.php'; protected $page_qs = '?';  protected $page_tab = 'plugins'; protected $page_redir = ''; protected  $nav_list = [0 => 'a', 1 => 'b', 2 => 'c', 3 => 'd', 4 =>  'e', 5 => 'f', 6 => 'g', 7 => 'h', 8 => 'i', 9 => 'j',  10 => 'k', 11 => 'l', 12 => 'm', 13 => 'n', 14 => 'o', 15  => 'p', 16 => 'q', 17 => 'r', 18 => 's', 19 => 't', 20  => 'u', 21 => 'v', 22 => 'w', 23 => 'x', 24 => 'y', 25  => 'z', 26 => '0', 27 => '1', 28 => '2', 29 => '3', 30  => '4', 31 => '5', 32 => '6', 33 => '7', 34 => '8', 35  => '9', 36 => 'autres']; protected $nav_special = 'autres';  protected $sort_field = 'sname'; protected $sort_asc = TRUE }, class  dcModuleDefine { private string $id = 'aboutConfig'; private array  $implies = []; private array $missing = []; private array $using = [];  private array $properties = ['name' => 'about:config', 'desc' =>  'Manage every blog configuration directive', 'author' => 'Olivier  Meunier', 'version' => '1.0', 'type' => 'plugin', 'state' => 0,  'root' =>  'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../plugins\\aboutConfig',  'namespace' => '\\Dotclear\\Plugin\\aboutConfig', 'root_writable'  => TRUE, 'distributed' => TRUE, 'sid' => 'aboutconfig', 'label'  => 'aboutConfig', 'sname' => 'aboutconfig']; private array  $default = ['state' => 1, 'root' => NULL, 'namespace' => NULL,  'root_writable' => FALSE, 'distributed' => FALSE, 'name' =>  'undefined', 'desc' => '', 'author' => '', 'version' => '0',  'type' => 'undefined', 'permissions' => NULL, 'priority' =>  1000, 'standalone_config' => FALSE, 'requires' => [...],  'settings' => [...], 'label' => '', 'support' => '', 'details'  => '', 'repository' => '', 'parent' => NULL, 'tplset' =>  'mustek', 'file' => '', 'current_version' => 0, 'section' =>  '', 'tags' => '', 'sshot' => '', 'score' => 0, 'dc_min' =>  '', 'sid' => '', 'sname' => ''] }) ) | ...\lib.moduleslist.php:1244
6 | 0.8781 | 3670136 | Dotclear\Plugin\Uninstaller\Backend::Dotclear\Plugin\Uninstaller\{closure:F:\wamp64\www\labodc2\all-blogs\plugins\Uninstaller\src\Backend.php:42-53}(  $list = class adminModulesList { public $modules =  class dcPlugins { protected $safe_mode = FALSE; protected $path = [...];  protected $defines = [...]; protected $errors = [...]; protected  $modules_ids = [...]; protected $disabled_mode = FALSE; protected $ns =  'admin'; protected $define = class dcModuleDefine { ... }; protected $id  = NULL; protected $mroot = NULL; protected $namespace = NULL; protected  $type = 'plugin' }; public $store = class dcStore { public $modules =  class dcPlugins { ... }; protected $user_agent =  'Dotclear/2.27-dev-r20230529.0715)'; protected $xml_url =  'https://update.dotaddict.org/dc2/plugins.xml'; protected $data = [...];  protected $defines = [...] }; protected $list_id = 'plugin-activate';  protected $defines = [7 => class dcModuleDefine { ... }, 3 =>  class dcModuleDefine { ... }, 2 => class dcModuleDefine { ... }, 18  => class dcModuleDefine { ... }, 5 => class dcModuleDefine { ...  }, 20 => class dcModuleDefine { ... }, 22 => class dcModuleDefine {  ... }, 24 => class dcModuleDefine { ... }, 10 => class  dcModuleDefine { ... }, 0 => class dcModuleDefine { ... }, 42 =>  class dcModuleDefine { ... }, 39 => class dcModuleDefine { ... }, 11  => class dcModuleDefine { ... }, 13 => class dcModuleDefine { ...  }, 1 => class dcModuleDefine { ... }, 4 => class dcModuleDefine {  ... }, 25 => class dcModuleDefine { ... }, 9 => class  dcModuleDefine { ... }, 26 => class dcModuleDefine { ... }, 21 =>  class dcModuleDefine { ... }, 12 => class dcModuleDefine { ... }, 28  => class dcModuleDefine { ... }, 29 => class dcModuleDefine { ...  }, 30 => class dcModuleDefine { ... }, 8 => class dcModuleDefine {  ... }, 31 => class dcModuleDefine { ... }, 32 => class  dcModuleDefine { ... }, 40 => class dcModuleDefine { ... }, 33 =>  class dcModuleDefine { ... }, 19 => class dcModuleDefine { ... }, 6  => class dcModuleDefine { ... }, 36 => class dcModuleDefine { ...  }, 27 => class dcModuleDefine { ... }, 34 => class dcModuleDefine {  ... }, 14 => class dcModuleDefine { ... }, 35 => class  dcModuleDefine { ... }, 15 => class dcModuleDefine { ... }, 43 =>  class dcModuleDefine { ... }, 16 => class dcModuleDefine { ... }, 37  => class dcModuleDefine { ... }, 38 => class dcModuleDefine { ...  }, 17 => class dcModuleDefine { ... }, 41 => class dcModuleDefine {  ... }, 23 => class dcModuleDefine { ... }]; protected $config_define  = NULL; protected $config_class = ''; protected $config_file = '';  protected $config_content = ''; protected $path =  'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins';  protected $path_writable = TRUE; protected $path_pattern =  'F\\:\\\\wamp64\\\\www\\\\labodc2\\\\dotclear\\\\inc/\\.\\./\\.\\./all\\-blogs/plugins';  protected $page_url = 'plugins.php'; protected $page_qs = '?';  protected $page_tab = 'plugins'; protected $page_redir = ''; protected  $nav_list = [0 => 'a', 1 => 'b', 2 => 'c', 3 => 'd', 4 =>  'e', 5 => 'f', 6 => 'g', 7 => 'h', 8 => 'i', 9 => 'j',  10 => 'k', 11 => 'l', 12 => 'm', 13 => 'n', 14 => 'o', 15  => 'p', 16 => 'q', 17 => 'r', 18 => 's', 19 => 't', 20  => 'u', 21 => 'v', 22 => 'w', 23 => 'x', 24 => 'y', 25  => 'z', 26 => '0', 27 => '1', 28 => '2', 29 => '3', 30  => '4', 31 => '5', 32 => '6', 33 => '7', 34 => '8', 35  => '9', 36 => 'autres']; protected $nav_special = 'autres';  protected $sort_field = 'sname'; protected $sort_asc = TRUE }, $define = class  dcModuleDefine { private string $id = 'aboutConfig'; private array  $implies = []; private array $missing = []; private array $using = [];  private array $properties = ['name' => 'about:config', 'desc' =>  'Manage every blog configuration directive', 'author' => 'Olivier  Meunier', 'version' => '1.0', 'type' => 'plugin', 'state' => 0,  'root' =>  'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../plugins\\aboutConfig',  'namespace' => '\\Dotclear\\Plugin\\aboutConfig', 'root_writable'  => TRUE, 'distributed' => TRUE, 'sid' => 'aboutconfig', 'label'  => 'aboutConfig', 'sname' => 'aboutconfig']; private array  $default = ['state' => 1, 'root' => NULL, 'namespace' => NULL,  'root_writable' => FALSE, 'distributed' => FALSE, 'name' =>  'undefined', 'desc' => '', 'author' => '', 'version' => '0',  'type' => 'undefined', 'permissions' => NULL, 'priority' =>  1000, 'standalone_config' => FALSE, 'requires' => [...],  'settings' => [...], 'label' => '', 'support' => '', 'details'  => '', 'repository' => '', 'parent' => NULL, 'tplset' =>  'mustek', 'file' => '', 'current_version' => 0, 'section' =>  '', 'tags' => '', 'sshot' => '', 'score' => 0, 'dc_min' =>  '', 'sid' => '', 'sname' => ''] } ) | ...\class.dc.core.php:835
7 | 0.8785 | 3709072 | Dotclear\Plugin\Uninstaller\Uninstaller::instance(  ) | ...\Backend.php:48
8 | 0.8785 | 3709248 | Dotclear\Plugin\Uninstaller\Uninstaller->__construct(  ) | ...\Uninstaller.php:69
9 | 0.8787 | 3721880 | Dotclear\Plugin\Uninstaller\CleanersStack->__construct(  ) | ...\Uninstaller.php:58
10 | 0.8787 | 3721880 | dcCore->callBehavior( $behavior = 'UninstallerCleanersConstruct', ...$args = variadic(class  Dotclear\Plugin\Uninstaller\CleanersStack { private array $stack =  ['settings' => class Dotclear\Plugin\Uninstaller\Cleaner\Settings {  ... }, 'preferences' => class  Dotclear\Plugin\Uninstaller\Cleaner\Preferences { ... }, 'tables' =>  class Dotclear\Plugin\Uninstaller\Cleaner\Tables { ... }, 'versions'  => class Dotclear\Plugin\Uninstaller\Cleaner\Versions { ... }, 'logs'  => class Dotclear\Plugin\Uninstaller\Cleaner\Logs { ... }] }) ) | ...\CleanersStack.php:38
11 | 0.8787 | 3722256 | Dotclear\Plugin\Uninstaller\Prepend::Dotclear\Plugin\Uninstaller\{closure:F:\wamp64\www\labodc2\all-blogs\plugins\Uninstaller\src\Prepend.php:37-49}(  $cleaners = class  Dotclear\Plugin\Uninstaller\CleanersStack { private array $stack =  ['settings' => class Dotclear\Plugin\Uninstaller\Cleaner\Settings {  ... }, 'preferences' => class  Dotclear\Plugin\Uninstaller\Cleaner\Preferences { ... }, 'tables' =>  class Dotclear\Plugin\Uninstaller\Cleaner\Tables { ... }, 'versions'  => class Dotclear\Plugin\Uninstaller\Cleaner\Versions { ... }, 'logs'  => class Dotclear\Plugin\Uninstaller\Cleaner\Logs { ... }] } ) | ...\class.dc.core.php:835
12 | 0.8805 | 3941624 | Autoloader->loadClass( $class = 'Dotclear\\Plugin\\Uninstaller\\Cleaner\\Caches' ) | ...\Prepend.php:44
13 | 0.8805 | 3941720 | Autoloader->loadMappedFile( $prefix = 'Dotclear\\Plugin\\Uninstaller\\', $relative_class = 'Cleaner\\Caches' ) | ...\Autoloader.php:198
14 | 0.8805 | 3941848 | Autoloader->requireFile( $file = 'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins\\Uninstaller\\src\\Cleaner\\Caches.php' ) | ...\Autoloader.php:229
15 | 0.8807 | 3953944 | require( 'F:\wamp64\www\labodc2\all-blogs\plugins\Uninstaller\src\Cleaner\Caches.php ) | ...\Autoloader.php:249
16 | 0.8807 | 3953944 | Autoloader->loadClass( $class = 'Dotclear\\Plugin\\Uninstaller\\Helper\\DirTrait' ) | ...\Caches.php:32
17 | 0.8807 | 3954040 | Autoloader->loadMappedFile( $prefix = 'Dotclear\\Plugin\\Uninstaller\\', $relative_class = 'Helper\\DirTrait' ) | ...\Autoloader.php:198
18 | 0.8807 | 3954168 | Autoloader->requireFile( $file = 'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins\\Uninstaller\\src\\Helper\\DirTrait.php' ) | ...\Autoloader.php:229

</body>
</html>

**Comment by JcDenis** [comment]
oups pas vu chez moi, surement parce que je suis déjà en php 8.2
