### ISSUE TITLE
À étudier

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/Uninstaller#5]
J'intègrerai bien ton plugin à la 2.28 de mi-novembre et possiblement pas sous forme de plugin mais comme fonction intégrée (histoire de pouvoir l'utiliser en mode de secours).

Tu peux jeter un œil et me dire si c'est possible ?

**Comment by JcDenis** [comment]
Tout est possible ! Même si je n'avais pas prévu de l'intégrer autrement qu'en plugin.
Et j'aurais un peu de temps 2ème quinzaine d'aout pour me pencher dessus ;)

Question que veux tu en faire en mode de secours ?

**Comment by franck-paul** [comment]
Pour le mode de secours, ça risque d'être compliqué à la réflexion, puisque ça veut dire prendre en compte les Uninstall.php des plugins (soft/hard désactivés), ça peut poser problème.

On peut l'intégrer sous forme de plugin dans ce cas, pour la 2.28, ça sera plus simple effectivement.

**Comment by JcDenis** [comment]
Je réfléchie quand même à ce que pourrait donner son intégration dans le core et on en reparle.
